# Generated by Django 5.1.1 on 2024-09-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_scope_options_tag_tagline_alter_scope_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tagline',
        ),
    ]
